In [1]:
import torch

In [2]:
scalar = torch.tensor(700)

In [3]:
scalar

tensor(700)

In [4]:
type(scalar)

torch.Tensor

In [5]:
scalar.ndim

0

In [6]:
scalar.item() #Get the python number within a tensor

700

In [7]:
#Vector
vector = torch.tensor([5,6])
vector

tensor([5, 6])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#Matrix

mat = torch.tensor([[7,8],
                   [12,13]])
mat

tensor([[ 7,  8],
        [12, 13]])

In [11]:
mat.ndim

2

In [12]:
mat.shape

torch.Size([2, 2])

In [13]:
torch.rand(size=(4,3))

tensor([[0.8156, 0.2803, 0.2405],
        [0.0590, 0.8280, 0.7143],
        [0.3147, 0.6299, 0.5554],
        [0.0146, 0.1600, 0.5391]])

In [14]:
torch.rand(size=(224,224,3))

tensor([[[0.9737, 0.6434, 0.8525],
         [0.6504, 0.3057, 0.8737],
         [0.8642, 0.0283, 0.4362],
         ...,
         [0.5815, 0.4496, 0.9441],
         [0.8751, 0.1918, 0.5548],
         [0.2826, 0.7198, 0.9427]],

        [[0.6928, 0.1577, 0.0476],
         [0.6145, 0.6253, 0.5204],
         [0.4090, 0.6313, 0.7757],
         ...,
         [0.3721, 0.8440, 0.0145],
         [0.6127, 0.9815, 0.3933],
         [0.3461, 0.3993, 0.5504]],

        [[0.0410, 0.3531, 0.0751],
         [0.4027, 0.3109, 0.0606],
         [0.5888, 0.5555, 0.6791],
         ...,
         [0.5578, 0.8564, 0.2162],
         [0.9956, 0.5814, 0.7791],
         [0.4066, 0.9966, 0.3489]],

        ...,

        [[0.6737, 0.6796, 0.6283],
         [0.2239, 0.6818, 0.9819],
         [0.7062, 0.2760, 0.8457],
         ...,
         [0.0663, 0.3077, 0.4022],
         [0.3758, 0.1489, 0.0413],
         [0.9165, 0.3376, 0.2286]],

        [[0.0860, 0.2600, 0.2450],
         [0.8065, 0.6533, 0.7669],
         [0.

In [15]:
torch.range(11,19)

/tmp/ipython-input-4261411200.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(11,19)


tensor([11., 12., 13., 14., 15., 16., 17., 18., 19.])

https://docs.pytorch.org/docs/stable/tensors.html#data-types

In [16]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
             dtype=None, #defaults to none, which is torch.float32,
             device = None)

In [17]:
float_32_tensor.dtype

torch.float32

In [19]:
float_16_tensor = torch.tensor([3.0,6.0,9.0],
             dtype=torch.float16, #defaults to none, which is torch.float32,
             device = 'cpu')

In [20]:
float_16_tensor.dtype

torch.float16

In [21]:
float_16_tensor.device

device(type='cpu')

In [22]:
some_tensor = torch.rand(3,4)

In [23]:
some_tensor.shape

torch.Size([3, 4])

In [24]:
some_tensor.dtype

torch.float32

In [25]:
some_tensor.device

device(type='cpu')

In [27]:
some_tensor

tensor([[0.5057, 0.4031, 0.4782, 0.9307],
        [0.0453, 0.2218, 0.6519, 0.6779],
        [0.4157, 0.3289, 0.3564, 0.9687]])

In [30]:
some_tensor = torch.tensor([1,2,3])
some_tensor

tensor([1, 2, 3])

In [31]:
some_tensor*some_tensor

tensor([1, 4, 9])

In [32]:
torch.matmul(some_tensor, some_tensor)

tensor(14)

In [34]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

In [36]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [37]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [43]:
x = torch.arange(1,8)
x

tensor([1, 2, 3, 4, 5, 6, 7])

In [44]:
x.shape

torch.Size([7])

In [45]:
x_reshaped = x.reshape(1,7)

In [46]:
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7]])

In [47]:
x_reshaped.shape

torch.Size([1, 7])

In [50]:
#stack
torch.stack([x,x,x,x],dim=0)

tensor([[1, 2, 3, 4, 5, 6, 7],
        [1, 2, 3, 4, 5, 6, 7],
        [1, 2, 3, 4, 5, 6, 7],
        [1, 2, 3, 4, 5, 6, 7]])

In [54]:
x_reshaped.squeeze() #remove extra dimension

tensor([1, 2, 3, 4, 5, 6, 7])

In [56]:
x.unsqueeze(dim=0)

tensor([[1, 2, 3, 4, 5, 6, 7]])

In [57]:
x.unsqueeze(dim=1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7]])

In [58]:
import numpy as np

In [59]:
array = np.arange(1,8)
array

array([1, 2, 3, 4, 5, 6, 7])

In [60]:
torch.from_numpy(array)

tensor([1, 2, 3, 4, 5, 6, 7])

In [64]:
tensor_demo = torch.ones(4)
tensor_demo

tensor([1., 1., 1., 1.])

In [65]:
tensor_demo.numpy()

array([1., 1., 1., 1.], dtype=float32)