##### Importing Library

In [1]:
import numpy as np

##### Indexing

In [3]:
l1 = [1,2,3]
type(l1)

list

In [6]:
array_a1 = np.array([1,2,3])
array_a1

array([1, 2, 3])

In [7]:
my_mat = np.array([[1,2,3],[4,5,6]])
my_mat

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
nested_list = [[1,2,3],[4,5,6]]

In [10]:
nested_list[0][2]

3

In [12]:
my_mat[0][2]

np.int64(3)

In [13]:
my_mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
my_mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
my_mat1[0][1]

np.int64(2)

In [22]:
my_mat1[0][-2]

np.int64(2)

In [23]:
my_mat1[1][-1]

np.int64(6)

In [16]:
my_mat1[2]

array([7, 8, 9])

In [24]:
my_mat1[-1][-2] #or 1

np.int64(8)

In [18]:
my_mat1[-2]

array([4, 5, 6])

In [19]:
my_mat1[-3]

array([1, 2, 3])

In [25]:
my_mat2 = np.array([[11,12,13,21],[14,15,16,22],[17,18,19,23]])
my_mat2

array([[11, 12, 13, 21],
       [14, 15, 16, 22],
       [17, 18, 19, 23]])

In [28]:
my_mat2[1,2]

np.int64(16)

In [29]:
my_mat2[-2,2]

np.int64(16)

In [30]:
my_mat2[-2,-2]

np.int64(16)

In [31]:
my_mat2[1,-2]

np.int64(16)

In [32]:
my_mat2[0,-1] #-3,2

np.int64(21)

In [34]:
my_mat2[-1,1] #2,-3

np.int64(18)

##### Assigning Values

In [35]:
my_mat2[:,0]

array([11, 14, 17])

In [37]:
my_mat2[0,-1] = 99

In [38]:
my_mat2

array([[11, 12, 13, 99],
       [14, 15, 16, 22],
       [17, 18, 19, 23]])

In [40]:
my_mat2[0] = 101

In [41]:
my_mat2

array([[101, 101, 101, 101],
       [ 14,  15,  16,  22],
       [ 17,  18,  19,  23]])

In [44]:
my_mat2[:,-2] = 900

In [45]:
my_mat2

array([[101, 101, 900, 101],
       [ 14,  15, 900,  22],
       [ 17,  18, 900,  23]])

In [48]:
demo_list = [500,0,600,0]

In [50]:
my_mat2[1] = demo_list

In [51]:
my_mat2

array([[101, 101, 900, 101],
       [500,   0, 600,   0],
       [ 17,  18, 900,  23]])

In [55]:
my_mat2[:] = 999

In [56]:
my_mat2

array([[999, 999, 999, 999],
       [999, 999, 999, 999],
       [999, 999, 999, 999]])

In [58]:
my_mat2 = 999

In [59]:
my_mat2

999

##### Elementwise Properties

In [60]:
array_a = np.array([7,8,9])
array_b = np.array([[1,2,3],[4,5,6]])

In [61]:
array_a

array([7, 8, 9])

In [62]:
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
array_b*12

array([[12, 24, 36],
       [48, 60, 72]])

In [64]:
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
list_a = [1,2,3]
list_a + [2]

[1, 2, 3, 2]

In [66]:
array_a + 2

array([ 9, 10, 11])

In [68]:
array_a * array_b[1] #we multiple each element of array_a by its corresponding element in the b

array([28, 40, 54])

Types of data supported ny Numpy : float, complex, bool, str, int

In [70]:
array_b = np.array([[1,2,3],[4,5,6]],dtype=np.float16)
array_b

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)

In [71]:
array_b = np.array([[1,2,3],[4,5,6]],dtype=np.complex64)
array_b

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [74]:
array_b = np.array([[1,2,0],[4,5,6]],dtype=bool)
array_b

array([[ True,  True, False],
       [ True,  True,  True]])

In [75]:
array_b = np.array([[1,2,3],[4,5,6]],dtype=str)
array_b

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')

#### Built-in Methods to create arrays

In [76]:
#arange : return even space values within a given interval

np.arange(11,21)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [78]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [81]:
np.arange(11,21,4)

array([11, 15, 19])

In [84]:
np.arange(0,15,4)

array([ 0,  4,  8, 12])

In [85]:
#zeros : generate arrays of zeros
np.zeros(3)

array([0., 0., 0.])

In [86]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [87]:
#ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

##### Linspace

* return evenly spaced numbers over a specified interval

In [96]:
np.linspace(46,67,15)

array([46. , 47.5, 49. , 50.5, 52. , 53.5, 55. , 56.5, 58. , 59.5, 61. ,
       62.5, 64. , 65.5, 67. ])

# Eye

In [98]:
np.eye(5) #indentity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Array Attributes and Methods

In [114]:
arr = np.arange(25)

arr2 = np.linspace(0,50,100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [100]:
#reshape : return an array containing the same data with a new shape

arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [109]:
arr_2d = arr2.reshape(25,4)
arr_2d

array([[ 0.        ,  0.50505051,  1.01010101,  1.51515152],
       [ 2.02020202,  2.52525253,  3.03030303,  3.53535354],
       [ 4.04040404,  4.54545455,  5.05050505,  5.55555556],
       [ 6.06060606,  6.56565657,  7.07070707,  7.57575758],
       [ 8.08080808,  8.58585859,  9.09090909,  9.5959596 ],
       [10.1010101 , 10.60606061, 11.11111111, 11.61616162],
       [12.12121212, 12.62626263, 13.13131313, 13.63636364],
       [14.14141414, 14.64646465, 15.15151515, 15.65656566],
       [16.16161616, 16.66666667, 17.17171717, 17.67676768],
       [18.18181818, 18.68686869, 19.19191919, 19.6969697 ],
       [20.2020202 , 20.70707071, 21.21212121, 21.71717172],
       [22.22222222, 22.72727273, 23.23232323, 23.73737374],
       [24.24242424, 24.74747475, 25.25252525, 25.75757576],
       [26.26262626, 26.76767677, 27.27272727, 27.77777778],
       [28.28282828, 28.78787879, 29.29292929, 29.7979798 ],
       [30.3030303 , 30.80808081, 31.31313131, 31.81818182],
       [32.32323232, 32.

In [107]:
#Shape: attribute that arrays have. They will output the dimensional characteristics of the array
arr.shape

(25,)

In [112]:
arr_2d.shape

(25, 4)

In [113]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [116]:
arr.shape

(25,)

In [117]:
arr_2d_1 = arr.reshape(1,25)
arr_2d_1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [118]:
arr_2d_1.shape

(1, 25)

In [119]:
arr_2d_2 = arr.reshape(25,1)
arr_2d_2

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [120]:
arr_2d_2.shape

(25, 1)

* uniform distribution
* standard normal distribution


1. Create an 1D array of 30 elements
2. reshape it to 2d with 6 rows and 5 columns
3. Grab the any 5 elements at odd row/column. for eg (1,3)(3,5)