# Universal Array Functions (ufuncs)

In [1]:
import numpy as np

In [29]:
a = np.array([1,2,3,4])
b = np.array([10,2,30,40])
c = np.array([0.1,0.5,0.9,1.5])

### Arithmetic funcs

In [9]:
np.add(a,b)

array([11, 22, 33, 44])

In [10]:
np.subtract(a,b)

array([ -9, -18, -27, -36])

In [11]:
np.multiply(a,b)

array([ 10,  40,  90, 160])

In [12]:
np.divide(b,a)

array([10., 10., 10., 10.])

In [13]:
np.mod(b,a)

array([0, 0, 0, 0])

In [14]:
np.floor_divide(b,a)

array([10, 10, 10, 10])

In [16]:
np.power(a,4)

array([  1,  16,  81, 256])

In [18]:
np.lcm(12,20)

np.int64(60)

In [19]:
arr = [4,6,8]

In [22]:
np.lcm(4,6)

np.int64(12)

In [23]:
np.lcm(6,8)

np.int64(24)

In [24]:
np.lcm.reduce([4,6,8])

np.int64(24)

# Comparison Functions

In [30]:
np.greater(b,a)

array([ True, False,  True,  True])

In [31]:
np.less(b,a)

array([False, False, False, False])

In [32]:
np.equal(b,a)

array([False,  True, False, False])

In [33]:
np.not_equal(b,a)

array([ True, False,  True,  True])

3. Trigonometric Functions

In [34]:
c

array([0.1, 0.5, 0.9, 1.5])

In [35]:
np.sin(c)

array([0.09983342, 0.47942554, 0.78332691, 0.99749499])

In [36]:
np.degrees(1)

np.float64(57.29577951308232)

In [37]:
np.deg2rad([0,90,180])

array([0.        , 1.57079633, 3.14159265])

#exponential and logarithmic functions

In [38]:
np.exp(a) #exponential(e^x)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [39]:
np.log(c) #natural log

array([-2.30258509, -0.69314718, -0.10536052,  0.40546511])

In [40]:
np.log10(c) #base10 log

array([-1.        , -0.30103   , -0.04575749,  0.17609126])

# ROunding Functions

In [41]:
d = np.array([1.234,2.34567,3.4566787,6.78899])
d

array([1.234    , 2.34567  , 3.4566787, 6.78899  ])

In [42]:
#round
np.round(d,2)

array([1.23, 2.35, 3.46, 6.79])

In [43]:
#floor (round down)

np.floor(d)

array([1., 2., 3., 6.])

In [44]:
#ceil (round up)
np.ceil(d)

array([2., 3., 4., 7.])

In [45]:
#Truncation (remove decimal)

np.trunc(d)

array([1., 2., 3., 6.])

In [46]:
a

array([1, 2, 3, 4])

In [47]:
np.sum(a)

np.int64(10)

In [48]:
np.prod(a)

np.int64(24)

In [49]:
np.max(a)

np.int64(4)

In [50]:
np.min(a)

np.int64(1)

In [51]:
np.mean(a)

np.float64(2.5)

In [52]:
np.std(a)

np.float64(1.118033988749895)

In [53]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [54]:
np.square(a)

array([ 1,  4,  9, 16])

# Axis Logic

In [55]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr.sum()

np.int64(45)

In [57]:
arr.mean()

np.float64(4.5)

In [58]:
arr.max()

np.int64(9)

In [59]:
arr.min()

np.int64(0)

In [60]:
arr.var()

np.float64(8.25)

In [61]:
arr.std()

np.float64(2.8722813232690143)

# In 2-D arrays:

* axis0 : rows / vertical axis
* axis1 : columns / horizontal axis

In [62]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [64]:
arr_2d.sum(axis=1)

array([10, 26, 42])

In [65]:
arr_2d.var(axis=0)

array([10.66666667, 10.66666667, 10.66666667, 10.66666667])

In [66]:
arr_2d.var()

np.float64(11.916666666666666)

In [67]:
arr_2d.var(axis=1)

array([1.25, 1.25, 1.25])

In [68]:
arr_2d.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])